export const USER_REGISTERED_SUCCESSFULLY = 'USER_REGISTERED_SUCCESSFULLY';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED';
export const RECIPES = 'RECIPES';
